apiVersion: v2
appVersion: 1.4.0
description: Randoli App Insights Agent
home: https://randoli.ca
icon: https://s3.ca-central-1.amazonaws.com/randoli.ca/icons/icon-384x384.png
keywords:
- app-insights
- app-insights-agent
- randoli
maintainers:
- name: Randoli
  url: https://randoli.ca
  email: support@randoli.ca
name: app-insights-agent
sources:
- https://github.com/randoli/helm-charts
version: 1.0.0
dependencies:
  - name: opencost
    repository: https://randoli.github.io/helm-charts
    version: 1.27.0
    condition: opencost.enabled