global:
  prometheus:
    url: http://my-prometheus-server.prometheus.svc.cluster.local:80

image:
  registry: docker.io
  repository: randoli/insights-agent
  tag: "1.7"
  digest: ""
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: Always

imagePullSecrets: []

secrets:
  cert: insights-agent-cert
  config: insights-agent-secret

labels:
  app: app-insights-agent

deploymentAnnotations: {}

resources:
  limits:
    cpu: 150m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 256Mi

# -- Toleration labels for pod assignment
tolerations: []
# -- Node labels for pod assignment
nodeSelector: {}
# -- Affinity settings for pod assignment
affinity: {}
# -- Assign custom TopologySpreadConstraints rules
topologySpreadConstraints: []

extraEnv: []
extraEnvFrom: []

extraVolumes: []
extraVolumeMounts: []

securityContext: {}

serviceAccount:
  create: true
  # If not set and create is true, a name is generated using the fullname template
  # name: ""
  automountServiceAccountToken: true
  annotations: {}
  labels: {}

opencost:
  # If enabled, OpenCost will be deployed and does not need the URL
  enabled: true
  # If this URL is provided then it will replace the generated one
  url:

  opencost:
    ui:
      enabled: false
    metrics:
      kubeStateMetrics:
        emitKsmV1Metrics: false
        emitKsmV1MetricsOnly: false
      serviceMonitor:
        enabled: true

# If enabled, the agent will query for container logs to augment events
collectLogs: true

rightsizingRecommendations:
  enabled: true
  # If enabled, VerticalPodAutoscaler will be installed
  installVpa: false

securityScans:
  # Install kubescape-operator
  # Kubescape-operator is required to run security scans in the cluster
  installKubescape: false
 
  # Default value is OFF
  # OFF|INTERVAL_SCANNING
  mode: 'OFF'
  # Only required if INTERVAL_SCANNING is set as mode
  cronSpec: '0 9,20 * * *'

  # -- set the image pull secrets for private registry support
  imagePullSecrets: ""
  capabilities:
    continuousScan: enable