apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-insights-agent.fullname" . }}-config
  namespace: {{ include "app-insights-agent.namespace" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  AGENT_CONTROLLER_DIAL_TIMEOUT: 10000ms
  APP_NAME: app-insights-agent
  CLIENT_CERT_PATH: /app/certs/client-cert.pem
  CLIENT_PRIVATE_KEY_PATH: /app/certs/client-key.pem
  CONTEXT_PATH: /
  DEBUG: 'false'
  HTTP_SERVICE_PORT: '8080'
  KEYCLOAK_TIMEOUT: 1m0s
  {{ if .Values.opencost.url }}
  OPENCOST_BACKEND_URL: {{ .Values.opencost.url }}
  {{ else }}
  OPENCOST_BACKEND_URL: http://{{ .Release.Name }}-opencost.{{ .Release.Namespace }}.svc.cluster.local:9003
  {{ end }}
  PROMETHEUS_URL: {{ .Values.global.prometheus.url }}
  TLS_ENABLED: 'true'
  VENDOR_MAJOR_VERSION: ''
  VENDOR_MINOR_VERSION: ''
  VENDOR_NAME: ''
  VENDOR_VERSION: ''
